version: '3.9'
services:
  app:
    build:
      context: .
    ports:
      - "5000:5000"
    command: python app/app.py
  tests:
    build:
      context: .
    command: pytest tests/crud_test.py
    depends_on:
      - app
